---@class Eighties
---@field config EightiesConfig
---@field palette EightiesPalette
local Eighties = {}

local HEX_DIGITS = {
    ['0'] = 0,
    ['1'] = 1,
    ['2'] = 2,
    ['3'] = 3,
    ['4'] = 4,
    ['5'] = 5,
    ['6'] = 6,
    ['7'] = 7,
    ['8'] = 8,
    ['9'] = 9,
    ['a'] = 10,
    ['b'] = 11,
    ['c'] = 12,
    ['d'] = 13,
    ['e'] = 14,
    ['f'] = 15,
    ['A'] = 10,
    ['B'] = 11,
    ['C'] = 12,
    ['D'] = 13,
    ['E'] = 14,
    ['F'] = 15,
}
local function hex_to_rgb(hex)
    return HEX_DIGITS[string.sub(hex, 1, 1)] * 16 + HEX_DIGITS[string.sub(hex, 2, 2)],
        HEX_DIGITS[string.sub(hex, 3, 3)] * 16 + HEX_DIGITS[string.sub(hex, 4, 4)],
        HEX_DIGITS[string.sub(hex, 5, 5)] * 16 + HEX_DIGITS[string.sub(hex, 6, 6)]
end
local function rgb_to_hex(r, g, b)
    return bit.tohex(bit.bor(bit.lshift(r, 16), bit.lshift(g, 8), b), 6)
end
local function darken(hex, pct)
    pct = 1 - pct
    local r, g, b = hex_to_rgb(string.sub(hex, 2))
    r = math.floor(r * pct)
    g = math.floor(g * pct)
    b = math.floor(b * pct)
    return string.format("#%s", rgb_to_hex(r, g, b))
end

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class EightiesConfig
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
Eighties.config = {
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

-- main color palette
---@class EightiesPalette
Eighties.palette = {
  dark0 = "#2D2D2D",
  dark1 = "#393939",
  dark2 = "#515151",
  dark3 = "#747369",
  dark4 = "#999999",
  light0 = "#ffffff",
  light1 = "#e0e0e0",
  light2 = "#d6d6d6",
  light3 = "#b4b4b4",
  light4 = "#a09f93",
  red = "#f2777a",
  green = "#99cc99",
  yellow = "#ffcc66",
  blue = "#72aeea",
  purple = "#cc99cc",
  aqua = "#66cccc",
  orange = "#f9a170",
  gray = "#a09f93",
}

-- get a hex list of colors based on current bg and constrast config
local function get_colors()
  local p = Eighties.palette
  local config = Eighties.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  return {
    bg0 = p.dark0,
    bg1 = p.dark1,
    bg2 = p.dark2,
    bg3 = p.dark3,
    bg4 = p.dark4,
    fg0 = p.light0,
    fg1 = p.light1,
    fg2 = p.light2,
    fg3 = p.light3,
    fg4 = p.light4,
    red = p.red,
    green = p.green,
    yellow = p.yellow,
    blue = p.blue,
    purple = p.purple,
    aqua = p.aqua,
    orange = p.orange,
    gray = p.gray,
  }
end

local function get_groups()
  local colors = get_colors()
  local config = Eighties.config

  local darkerbg           = darken(colors.bg0, 0.1)
  local darkercursorline   = darken(colors.bg1, 0.1)
  local darkerstatusline   = darken(colors.bg2, 0.1)


  local groups = {
    EightiesFg0 = { fg = colors.fg0 },
    EightiesFg1 = { fg = colors.fg1 },
    EightiesFg2 = { fg = colors.fg2 },
    EightiesFg3 = { fg = colors.fg3 },
    EightiesFg4 = { fg = colors.fg4 },
    EightiesGray = { fg = colors.gray },
    EightiesBg0 = { fg = colors.bg0 },
    EightiesBg1 = { fg = colors.bg1 },
    EightiesBg2 = { fg = colors.bg2 },
    EightiesBg3 = { fg = colors.bg3 },
    EightiesBg4 = { fg = colors.bg4 },
    EightiesRed = { fg = colors.red },
    EightiesRedBold = { fg = colors.red, bold = config.bold },
    EightiesGreen = { fg = colors.green },
    EightiesGreenBold = { fg = colors.green, bold = config.bold },
    EightiesYellow = { fg = colors.yellow },
    EightiesYellowBold = { fg = colors.yellow, bold = config.bold },
    EightiesBlue = { fg = colors.blue },
    EightiesBlueBold = { fg = colors.blue, bold = config.bold },
    EightiesPurple = { fg = colors.purple },
    EightiesPurpleBold = { fg = colors.purple, bold = config.bold },
    EightiesAqua = { fg = colors.aqua },
    EightiesAquaBold = { fg = colors.aqua, bold = config.bold },
    EightiesOrange = { fg = colors.orange },
    EightiesOrangeBold = { fg = colors.orange, bold = config.bold },
    EightiesRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
        or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    EightiesGreenSign = config.transparent_mode and
        { fg = colors.green, reverse = config.invert_signs }
        or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    EightiesYellowSign = config.transparent_mode and
        { fg = colors.yellow, reverse = config.invert_signs }
        or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    EightiesBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
        or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    EightiesPurpleSign = config.transparent_mode and
        { fg = colors.purple, reverse = config.invert_signs }
        or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    EightiesAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
        or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    EightiesOrangeSign = config.transparent_mode and
        { fg = colors.orange, reverse = config.invert_signs }
        or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    EightiesRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    EightiesGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    EightiesYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    EightiesBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    EightiesPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    EightiesAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    EightiesOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "EightiesBg2" },
    SpecialKey = { link = "EightiesFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "EightiesBlueBold" },
    Title = { link = "EightiesGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "EightiesYellowBold" },
    ModeMsg = { link = "EightiesYellowBold" },
    Question = { link = "EightiesOrangeBold" },
    WarningMsg = { link = "EightiesRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "EightiesOrange" },
    Comment = { fg = colors.gray, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "EightiesRed" },
    Conditional = { link = "EightiesRed" },
    Repeat = { link = "EightiesRed" },
    Label = { link = "EightiesRed" },
    Exception = { link = "EightiesRed" },
    Operator = { fg = colors.orange, italic = config.italic.operators },
    Keyword = { link = "EightiesRed" },
    Identifier = { link = "EightiesBlue" },
    Function = { link = "EightiesGreenBold" },
    PreProc = { link = "EightiesAqua" },
    Include = { link = "EightiesAqua" },
    Define = { link = "EightiesAqua" },
    Macro = { link = "EightiesAqua" },
    PreCondit = { link = "EightiesAqua" },
    Constant = { link = "EightiesPurple" },
    Character = { link = "EightiesPurple" },
    String = { fg = colors.green, italic = config.italic.strings },
    Boolean = { link = "EightiesPurple" },
    Number = { link = "EightiesPurple" },
    Float = { link = "EightiesPurple" },
    Type = { link = "EightiesYellow" },
    StorageClass = { link = "EightiesOrange" },
    Structure = { link = "EightiesAqua" },
    Typedef = { link = "EightiesYellow" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.red },
    DiffAdd = { bg = colors.green },
    DiffChange = { bg = colors.aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "EightiesBlueUnderline" },
    SpellBad = { link = "EightiesRedUnderline" },
    SpellLocal = { link = "EightiesAquaUnderline" },
    SpellRare = { link = "EightiesPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    DiagnosticError = { link = "EightiesRed" },
    DiagnosticSignError = { link = "EightiesRedSign" },
    DiagnosticUnderlineError = { link = "EightiesRedUnderline" },
    DiagnosticWarn = { link = "EightiesYellow" },
    DiagnosticSignWarn = { link = "EightiesYellowSign" },
    DiagnosticUnderlineWarn = { link = "EightiesYellowUnderline" },
    DiagnosticInfo = { link = "EightiesBlue" },
    DiagnosticSignInfo = { link = "EightiesBlueSign" },
    DiagnosticUnderlineInfo = { link = "EightiesBlueUnderline" },
    DiagnosticHint = { link = "EightiesAqua" },
    DiagnosticSignHint = { link = "EightiesAquaSign" },
    DiagnosticUnderlineHint = { link = "EightiesAquaUnderline" },
    DiagnosticFloatingError = { link = "EightiesRed" },
    DiagnosticFloatingWarn = { link = "EightiesOrange" },
    DiagnosticFloatingInfo = { link = "EightiesBlue" },
    DiagnosticFloatingHint = { link = "EightiesAqua" },
    DiagnosticVirtualTextError = { link = "EightiesRed" },
    DiagnosticVirtualTextWarn = { link = "EightiesYellow" },
    DiagnosticVirtualTextInfo = { link = "EightiesBlue" },
    DiagnosticVirtualTextHint = { link = "EightiesAqua" },
    DiagnosticOk = { link = "EightiesGreenSign" },
    LspReferenceRead = { link = "EightiesYellowBold" },
    LspReferenceText = { link = "EightiesYellowBold" },
    LspReferenceWrite = { link = "EightiesOrangeBold" },
    LspCodeLens = { link = "EightiesGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "EightiesGreen" },
    gitcommitDiscardedFile = { link = "EightiesRed" },
    GitSignsAdd = { link = "EightiesGreenSign" },
    GitSignsChange = { link = "EightiesAquaSign" },
    GitSignsDelete = { link = "EightiesRedSign" },
    NvimTreeSymlink = { fg = colors.aqua },
    NvimTreeRootFolder = { fg = colors.purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.blue, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.green, bold = true },
    NvimTreeOpenedFile = { fg = colors.red, bold = true },
    NvimTreeSpecialFile = { fg = colors.yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.purple },
    NvimTreeIndentMarker = { fg = colors.dark3 },
    NvimTreeGitDirty = { fg = colors.yellow },
    NvimTreeGitStaged = { fg = colors.yellow },
    NvimTreeGitMerge = { fg = colors.purple },
    NvimTreeGitRenamed = { fg = colors.purple },
    NvimTreeGitNew = { fg = colors.yellow },
    NvimTreeGitDeleted = { fg = colors.red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    debugPC = { bg = colors.blue },
    debugBreakpoint = { link = "EightiesRedSign" },
    StartifyBracket = { link = "EightiesFg3" },
    StartifyFile = { link = "EightiesFg1" },
    StartifyNumber = { link = "EightiesBlue" },
    StartifyPath = { link = "EightiesGray" },
    StartifySlash = { link = "EightiesGray" },
    StartifySection = { link = "EightiesYellow" },
    StartifySpecial = { link = "EightiesBg2" },
    StartifyHeader = { link = "EightiesOrange" },
    StartifyFooter = { link = "EightiesBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "EightiesAqua" },
    DirvishArg = { link = "EightiesYellow" },
    netrwDir = { link = "EightiesAqua" },
    netrwClassify = { link = "EightiesAqua" },
    netrwLink = { link = "EightiesGray" },
    netrwSymLink = { link = "EightiesFg1" },
    netrwExe = { link = "EightiesYellow" },
    netrwComment = { link = "EightiesGray" },
    netrwList = { link = "EightiesBlue" },
    netrwHelpCmd = { link = "EightiesAqua" },
    netrwCmdSep = { link = "EightiesFg3" },
    netrwVersion = { link = "EightiesGreen" },
    NERDTreeDir = { link = "EightiesAqua" },
    NERDTreeDirSlash = { link = "EightiesAqua" },
    NERDTreeOpenable = { link = "EightiesOrange" },
    NERDTreeClosable = { link = "EightiesOrange" },
    NERDTreeFile = { link = "EightiesFg1" },
    NERDTreeExecFile = { link = "EightiesYellow" },
    NERDTreeUp = { link = "EightiesGray" },
    NERDTreeCWD = { link = "EightiesGreen" },
    NERDTreeHelp = { link = "EightiesFg1" },
    NERDTreeToggleOn = { link = "EightiesGreen" },
    NERDTreeToggleOff = { link = "EightiesRed" },
    CocErrorSign = { link = "EightiesRedSign" },
    CocWarningSign = { link = "EightiesOrangeSign" },
    CocInfoSign = { link = "EightiesBlueSign" },
    CocHintSign = { link = "EightiesAquaSign" },
    CocErrorFloat = { link = "EightiesRed" },
    CocWarningFloat = { link = "EightiesOrange" },
    CocInfoFloat = { link = "EightiesBlue" },
    CocHintFloat = { link = "EightiesAqua" },
    CocDiagnosticsError = { link = "EightiesRed" },
    CocDiagnosticsWarning = { link = "EightiesOrange" },
    CocDiagnosticsInfo = { link = "EightiesBlue" },
    CocDiagnosticsHint = { link = "EightiesAqua" },
    CocSelectedText = { link = "EightiesRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "EightiesGray" },
    CocErrorHighlight = { link = "EightiesRedUnderline" },
    CocWarningHighlight = { link = "EightiesOrangeUnderline" },
    CocInfoHighlight = { link = "EightiesBlueUnderline" },
    CocHintHighlight = { link = "EightiesAquaUnderline" },
    -- telescope
    -- old
    TelescopeNormal = { link = "EightiesFg1" },
    TelescopeSelection = { link = "EightiesOrangeBold" },
    TelescopeSelectionCaret = { link = "EightiesRed" },
    TelescopeMultiSelection = { link = "EightiesGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "EightiesBlue" },
    TelescopePromptPrefix = { link = "EightiesRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    -- new
    -- telescope.nvim
    TelescopeSelectionCaret = { link = "EightiesGray" },
    TelescopeMultiSelection = { link = "EightiesGray" },
    TelescopeMatching       = { link = "EightiesBlue" },
    TelescopePrompt         = { link = "TelescopeNormal" },
    TelescopeBorder         = { fg = darkerbg, bg = darkerbg},
    TelescopeResultsBorder  = { link = "TelescopeBorder" },
    TelescopePreviewBorder  = { link = "TelescopeBorder" },
    TelescopePreview        = { bg = colors.bg1 },
    TelescopePromptBorder   = { fg = darkerstatusline, bg = darkerstatusline},
    TelescopePromptNormal   = { fg = colors.fg1, bg = darkerstatusline},
    TelescopePromptPrefix   = { fg = colors.yellow, bg = darkerstatusline},
    TelescopeNormal         = { fg = colors.fg1, bg = darkerbg},
    TelescopePreviewTitle   = { fg = darkercursorline, bg = colors.green},
    TelescopePromptTitle    = { fg = darkercursorline, bg = colors.red},
    TelescopeResultsTitle   = { fg = darkerbg, bg = darkerbg},
    TelescopeSelection      = { fg = nil, bg = darkerstatusline},
    TelescopePreviewLine    = { fg = nil, bg = colors.bg1},

    CmpItemAbbr = { link = "EightiesFg0" },
    CmpItemAbbrDeprecated = { link = "EightiesFg1" },
    CmpItemAbbrMatch = { link = "EightiesBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "EightiesBlueUnderline" },
    CmpItemMenu = { link = "EightiesGray" },
    CmpItemKindText = { link = "EightiesOrange" },
    CmpItemKindVariable = { link = "EightiesOrange" },
    CmpItemKindMethod = { link = "EightiesBlue" },
    CmpItemKindFunction = { link = "EightiesBlue" },
    CmpItemKindConstructor = { link = "EightiesYellow" },
    CmpItemKindUnit = { link = "EightiesBlue" },
    CmpItemKindField = { link = "EightiesBlue" },
    CmpItemKindClass = { link = "EightiesYellow" },
    CmpItemKindInterface = { link = "EightiesYellow" },
    CmpItemKindModule = { link = "EightiesBlue" },
    CmpItemKindProperty = { link = "EightiesBlue" },
    CmpItemKindValue = { link = "EightiesOrange" },
    CmpItemKindEnum = { link = "EightiesYellow" },
    CmpItemKindOperator = { link = "EightiesYellow" },
    CmpItemKindKeyword = { link = "EightiesPurple" },
    CmpItemKindEvent = { link = "EightiesPurple" },
    CmpItemKindReference = { link = "EightiesPurple" },
    CmpItemKindColor = { link = "EightiesPurple" },
    CmpItemKindSnippet = { link = "EightiesGreen" },
    CmpItemKindFile = { link = "EightiesBlue" },
    CmpItemKindFolder = { link = "EightiesBlue" },
    CmpItemKindEnumMember = { link = "EightiesAqua" },
    CmpItemKindConstant = { link = "EightiesOrange" },
    CmpItemKindStruct = { link = "EightiesYellow" },
    CmpItemKindTypeParameter = { link = "EightiesYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "EightiesOrange" },
    diffNewFile = { link = "EightiesYellow" },
    diffOldFile = { link = "EightiesOrange" },
    diffLine = { link = "EightiesBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "EightiesBlue" },
    NavicIconsModule = { link = "EightiesOrange" },
    NavicIconsNamespace = { link = "EightiesBlue" },
    NavicIconsPackage = { link = "EightiesAqua" },
    NavicIconsClass = { link = "EightiesYellow" },
    NavicIconsMethod = { link = "EightiesBlue" },
    NavicIconsProperty = { link = "EightiesAqua" },
    NavicIconsField = { link = "EightiesPurple" },
    NavicIconsConstructor = { link = "EightiesBlue" },
    NavicIconsEnum = { link = "EightiesPurple" },
    NavicIconsInterface = { link = "EightiesGreen" },
    NavicIconsFunction = { link = "EightiesBlue" },
    NavicIconsVariable = { link = "EightiesPurple" },
    NavicIconsConstant = { link = "EightiesOrange" },
    NavicIconsString = { link = "EightiesGreen" },
    NavicIconsNumber = { link = "EightiesOrange" },
    NavicIconsBoolean = { link = "EightiesOrange" },
    NavicIconsArray = { link = "EightiesOrange" },
    NavicIconsObject = { link = "EightiesOrange" },
    NavicIconsKey = { link = "EightiesAqua" },
    NavicIconsNull = { link = "EightiesOrange" },
    NavicIconsEnumMember = { link = "EightiesYellow" },
    NavicIconsStruct = { link = "EightiesPurple" },
    NavicIconsEvent = { link = "EightiesYellow" },
    NavicIconsOperator = { link = "EightiesRed" },
    NavicIconsTypeParameter = { link = "EightiesRed" },
    NavicText = { link = "EightiesWhite" },
    NavicSeparator = { link = "EightiesWhite" },
    htmlTag = { link = "EightiesAquaBold" },
    htmlEndTag = { link = "EightiesAquaBold" },
    htmlTagName = { link = "EightiesBlue" },
    htmlArg = { link = "EightiesOrange" },
    htmlTagN = { link = "EightiesFg1" },
    htmlSpecialTagName = { link = "EightiesBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "EightiesRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "EightiesAquaBold" },
    xmlEndTag = { link = "EightiesAquaBold" },
    xmlTagName = { link = "EightiesBlue" },
    xmlEqual = { link = "EightiesBlue" },
    docbkKeyword = { link = "EightiesAquaBold" },
    xmlDocTypeDecl = { link = "EightiesGray" },
    xmlDocTypeKeyword = { link = "EightiesPurple" },
    xmlCdataStart = { link = "EightiesGray" },
    xmlCdataCdata = { link = "EightiesPurple" },
    dtdFunction = { link = "EightiesGray" },
    dtdTagName = { link = "EightiesPurple" },
    xmlAttrib = { link = "EightiesOrange" },
    xmlProcessingDelim = { link = "EightiesGray" },
    dtdParamEntityPunct = { link = "EightiesGray" },
    dtdParamEntityDPunct = { link = "EightiesGray" },
    xmlAttribPunct = { link = "EightiesGray" },
    xmlEntity = { link = "EightiesRed" },
    xmlEntityPunct = { link = "EightiesRed" },
    clojureKeyword = { link = "EightiesBlue" },
    clojureCond = { link = "EightiesOrange" },
    clojureSpecial = { link = "EightiesOrange" },
    clojureDefine = { link = "EightiesOrange" },
    clojureFunc = { link = "EightiesYellow" },
    clojureRepeat = { link = "EightiesYellow" },
    clojureCharacter = { link = "EightiesAqua" },
    clojureStringEscape = { link = "EightiesAqua" },
    clojureException = { link = "EightiesRed" },
    clojureRegexp = { link = "EightiesAqua" },
    clojureRegexpEscape = { link = "EightiesAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "EightiesFg3" },
    clojureAnonArg = { link = "EightiesYellow" },
    clojureVariable = { link = "EightiesBlue" },
    clojureMacro = { link = "EightiesOrange" },
    clojureMeta = { link = "EightiesYellow" },
    clojureDeref = { link = "EightiesYellow" },
    clojureQuote = { link = "EightiesYellow" },
    clojureUnquote = { link = "EightiesYellow" },
    cOperator = { link = "EightiesPurple" },
    cppOperator = { link = "EightiesPurple" },
    cStructure = { link = "EightiesOrange" },
    pythonBuiltin = { link = "EightiesOrange" },
    pythonBuiltinObj = { link = "EightiesOrange" },
    pythonBuiltinFunc = { link = "EightiesOrange" },
    pythonFunction = { link = "EightiesAqua" },
    pythonDecorator = { link = "EightiesRed" },
    pythonInclude = { link = "EightiesBlue" },
    pythonImport = { link = "EightiesBlue" },
    pythonRun = { link = "EightiesBlue" },
    pythonCoding = { link = "EightiesBlue" },
    pythonOperator = { link = "EightiesRed" },
    pythonException = { link = "EightiesRed" },
    pythonExceptions = { link = "EightiesPurple" },
    pythonBoolean = { link = "EightiesPurple" },
    pythonDot = { link = "EightiesFg3" },
    pythonConditional = { link = "EightiesRed" },
    pythonRepeat = { link = "EightiesRed" },
    pythonDottedName = { link = "EightiesGreenBold" },
    cssBraces = { link = "EightiesBlue" },
    cssFunctionName = { link = "EightiesYellow" },
    cssIdentifier = { link = "EightiesOrange" },
    cssClassName = { link = "EightiesGreen" },
    cssColor = { link = "EightiesBlue" },
    cssSelectorOp = { link = "EightiesBlue" },
    cssSelectorOp2 = { link = "EightiesBlue" },
    cssImportant = { link = "EightiesGreen" },
    cssVendor = { link = "EightiesFg1" },
    cssTextProp = { link = "EightiesAqua" },
    cssAnimationProp = { link = "EightiesAqua" },
    cssUIProp = { link = "EightiesYellow" },
    cssTransformProp = { link = "EightiesAqua" },
    cssTransitionProp = { link = "EightiesAqua" },
    cssPrintProp = { link = "EightiesAqua" },
    cssPositioningProp = { link = "EightiesYellow" },
    cssBoxProp = { link = "EightiesAqua" },
    cssFontDescriptorProp = { link = "EightiesAqua" },
    cssFlexibleBoxProp = { link = "EightiesAqua" },
    cssBorderOutlineProp = { link = "EightiesAqua" },
    cssBackgroundProp = { link = "EightiesAqua" },
    cssMarginProp = { link = "EightiesAqua" },
    cssListProp = { link = "EightiesAqua" },
    cssTableProp = { link = "EightiesAqua" },
    cssFontProp = { link = "EightiesAqua" },
    cssPaddingProp = { link = "EightiesAqua" },
    cssDimensionProp = { link = "EightiesAqua" },
    cssRenderProp = { link = "EightiesAqua" },
    cssColorProp = { link = "EightiesAqua" },
    cssGeneratedContentProp = { link = "EightiesAqua" },
    javaScriptBraces = { link = "EightiesFg1" },
    javaScriptFunction = { link = "EightiesAqua" },
    javaScriptIdentifier = { link = "EightiesRed" },
    javaScriptMember = { link = "EightiesBlue" },
    javaScriptNumber = { link = "EightiesPurple" },
    javaScriptNull = { link = "EightiesPurple" },
    javaScriptParens = { link = "EightiesFg3" },
    typescriptReserved = { link = "EightiesAqua" },
    typescriptLabel = { link = "EightiesAqua" },
    typescriptFuncKeyword = { link = "EightiesAqua" },
    typescriptIdentifier = { link = "EightiesOrange" },
    typescriptBraces = { link = "EightiesFg1" },
    typescriptEndColons = { link = "EightiesFg1" },
    typescriptDOMObjects = { link = "EightiesFg1" },
    typescriptAjaxMethods = { link = "EightiesFg1" },
    typescriptLogicSymbols = { link = "EightiesFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "EightiesFg1" },
    typescriptParens = { link = "EightiesFg3" },
    typescriptOpSymbols = { link = "EightiesFg3" },
    typescriptHtmlElemProperties = { link = "EightiesFg1" },
    typescriptNull = { link = "EightiesPurple" },
    typescriptInterpolationDelimiter = { link = "EightiesAqua" },
    purescriptModuleKeyword = { link = "EightiesAqua" },
    purescriptModuleName = { link = "EightiesFg1" },
    purescriptWhere = { link = "EightiesAqua" },
    purescriptDelimiter = { link = "EightiesFg4" },
    purescriptType = { link = "EightiesFg1" },
    purescriptImportKeyword = { link = "EightiesAqua" },
    purescriptHidingKeyword = { link = "EightiesAqua" },
    purescriptAsKeyword = { link = "EightiesAqua" },
    purescriptStructure = { link = "EightiesAqua" },
    purescriptOperator = { link = "EightiesBlue" },
    purescriptTypeVar = { link = "EightiesFg1" },
    purescriptConstructor = { link = "EightiesFg1" },
    purescriptFunction = { link = "EightiesFg1" },
    purescriptConditional = { link = "EightiesOrange" },
    purescriptBacktick = { link = "EightiesOrange" },
    coffeeExtendedOp = { link = "EightiesFg3" },
    coffeeSpecialOp = { link = "EightiesFg3" },
    coffeeCurly = { link = "EightiesOrange" },
    coffeeParen = { link = "EightiesFg3" },
    coffeeBracket = { link = "EightiesOrange" },
    rubyStringDelimiter = { link = "EightiesGreen" },
    rubyInterpolationDelimiter = { link = "EightiesAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "EightiesRed" },
    objcDirective = { link = "EightiesBlue" },
    goDirective = { link = "EightiesAqua" },
    goConstants = { link = "EightiesPurple" },
    goDeclaration = { link = "EightiesRed" },
    goDeclType = { link = "EightiesBlue" },
    goBuiltins = { link = "EightiesOrange" },
    luaIn = { link = "EightiesRed" },
    luaFunction = { link = "EightiesAqua" },
    luaTable = { link = "EightiesOrange" },
    moonSpecialOp = { link = "EightiesFg3" },
    moonExtendedOp = { link = "EightiesFg3" },
    moonFunction = { link = "EightiesFg3" },
    moonObject = { link = "EightiesYellow" },
    javaAnnotation = { link = "EightiesBlue" },
    javaDocTags = { link = "EightiesAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "EightiesFg3" },
    javaParen1 = { link = "EightiesFg3" },
    javaParen2 = { link = "EightiesFg3" },
    javaParen3 = { link = "EightiesFg3" },
    javaParen4 = { link = "EightiesFg3" },
    javaParen5 = { link = "EightiesFg3" },
    javaOperator = { link = "EightiesOrange" },
    javaVarArg = { link = "EightiesGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "EightiesGreen" },
    elixirInterpolationDelimiter = { link = "EightiesAqua" },
    elixirModuleDeclaration = { link = "EightiesYellow" },
    scalaNameDefinition = { link = "EightiesFg1" },
    scalaCaseFollowing = { link = "EightiesFg1" },
    scalaCapitalWord = { link = "EightiesFg1" },
    scalaTypeExtension = { link = "EightiesFg1" },
    scalaKeyword = { link = "EightiesRed" },
    scalaKeywordModifier = { link = "EightiesRed" },
    scalaSpecial = { link = "EightiesAqua" },
    scalaOperator = { link = "EightiesFg1" },
    scalaTypeDeclaration = { link = "EightiesYellow" },
    scalaTypeTypePostDeclaration = { link = "EightiesYellow" },
    scalaInstanceDeclaration = { link = "EightiesFg1" },
    scalaInterpolation = { link = "EightiesAqua" },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "EightiesGreenBold" },
    markdownH2 = { link = "EightiesGreenBold" },
    markdownH3 = { link = "EightiesYellowBold" },
    markdownH4 = { link = "EightiesYellowBold" },
    markdownH5 = { link = "EightiesYellow" },
    markdownH6 = { link = "EightiesYellow" },
    markdownCode = { link = "EightiesAqua" },
    markdownCodeBlock = { link = "EightiesAqua" },
    markdownCodeDelimiter = { link = "EightiesAqua" },
    markdownBlockquote = { link = "EightiesGray" },
    markdownListMarker = { link = "EightiesGray" },
    markdownOrderedListMarker = { link = "EightiesGray" },
    markdownRule = { link = "EightiesGray" },
    markdownHeadingRule = { link = "EightiesGray" },
    markdownUrlDelimiter = { link = "EightiesFg3" },
    markdownLinkDelimiter = { link = "EightiesFg3" },
    markdownLinkTextDelimiter = { link = "EightiesFg3" },
    markdownHeadingDelimiter = { link = "EightiesOrange" },
    markdownUrl = { link = "EightiesPurple" },
    markdownUrlTitleDelimiter = { link = "EightiesGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "EightiesBlue" },
    haskellIdentifier = { link = "EightiesAqua" },
    haskellSeparator = { link = "EightiesFg4" },
    haskellDelimiter = { link = "EightiesOrange" },
    haskellOperators = { link = "EightiesPurple" },
    haskellBacktick = { link = "EightiesOrange" },
    haskellStatement = { link = "EightiesPurple" },
    haskellConditional = { link = "EightiesPurple" },
    haskellLet = { link = "EightiesRed" },
    haskellDefault = { link = "EightiesRed" },
    haskellWhere = { link = "EightiesRed" },
    haskellBottom = { link = "EightiesRedBold" },
    haskellImportKeywords = { link = "EightiesPurpleBold" },
    haskellDeclKeyword = { link = "EightiesOrange" },
    haskellDecl = { link = "EightiesOrange" },
    haskellDeriving = { link = "EightiesPurple" },
    haskellAssocType = { link = "EightiesAqua" },
    haskellNumber = { link = "EightiesAqua" },
    haskellPragma = { link = "EightiesRedBold" },
    haskellTH = { link = "EightiesAquaBold" },
    haskellForeignKeywords = { link = "EightiesGreen" },
    haskellKeyword = { link = "EightiesRed" },
    haskellFloat = { link = "EightiesAqua" },
    haskellInfix = { link = "EightiesPurple" },
    haskellQuote = { link = "EightiesGreenBold" },
    haskellShebang = { link = "EightiesYellowBold" },
    haskellLiquid = { link = "EightiesPurpleBold" },
    haskellQuasiQuoted = { link = "EightiesBlueBold" },
    haskellRecursiveDo = { link = "EightiesPurple" },
    haskellQuotedType = { link = "EightiesRed" },
    haskellPreProc = { link = "EightiesFg4" },
    haskellTypeRoles = { link = "EightiesRedBold" },
    haskellTypeForall = { link = "EightiesRed" },
    haskellPatternKeyword = { link = "EightiesBlue" },
    jsonKeyword = { link = "EightiesGreen" },
    jsonQuote = { link = "EightiesGreen" },
    jsonBraces = { link = "EightiesFg1" },
    jsonString = { link = "EightiesFg1" },
    mailQuoted1 = { link = "EightiesAqua" },
    mailQuoted2 = { link = "EightiesPurple" },
    mailQuoted3 = { link = "EightiesYellow" },
    mailQuoted4 = { link = "EightiesGreen" },
    mailQuoted5 = { link = "EightiesRed" },
    mailQuoted6 = { link = "EightiesOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "EightiesFg1" },
    csEndColon = { link = "EightiesFg1" },
    csLogicSymbols = { link = "EightiesFg1" },
    csParens = { link = "EightiesFg3" },
    csOpSymbols = { link = "EightiesFg3" },
    csInterpolationDelimiter = { link = "EightiesFg3" },
    csInterpolationAlignDel = { link = "EightiesAquaBold" },
    csInterpolationFormat = { link = "EightiesAqua" },
    csInterpolationFormatDel = { link = "EightiesAquaBold" },
    rustSigil = { link = "EightiesOrange" },
    rustEscape = { link = "EightiesAqua" },
    rustStringContinuation = { link = "EightiesAqua" },
    rustEnum = { link = "EightiesAqua" },
    rustStructure = { link = "EightiesAqua" },
    rustModPathSep = { link = "EightiesFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "EightiesAqua" },
    ocamlOperator = { link = "EightiesFg1" },
    ocamlKeyChar = { link = "EightiesOrange" },
    ocamlArrow = { link = "EightiesOrange" },
    ocamlInfixOpKeyword = { link = "EightiesRed" },
    ocamlConstructor = { link = "EightiesOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "EightiesFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "EightiesFg1" },
    LspSagaAutoPreview = { link = "EightiesOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "EightiesAqua" },
    LspSagaDefPreviewBorder = { link = "EightiesBlue" },
    LspSagaHoverBorder = { link = "EightiesOrange" },
    LspSagaRenameBorder = { link = "EightiesBlue" },
    LspSagaDiagnosticSource = { link = "EightiesOrange" },
    LspSagaDiagnosticBorder = { link = "EightiesPurple" },
    LspSagaDiagnosticHeader = { link = "EightiesGreen" },
    LspSagaSignatureHelpBorder = { link = "EightiesGreen" },
    SagaShadow = { link = "EightiesBg0" },
    DashboardShortCut = { link = "EightiesOrange" },
    DashboardHeader = { link = "EightiesAqua" },
    DashboardCenter = { link = "EightiesYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "EightiesAqua" },
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg4 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "EightiesFg1" },
    CarbonExe = { link = "EightiesYellow" },
    CarbonSymlink = { link = "EightiesAqua" },
    CarbonBrokenSymlink = { link = "EightiesRed" },
    CarbonIndicator = { link = "EightiesGray" },
    CarbonDanger = { link = "EightiesRed" },
    CarbonPending = { link = "EightiesYellow" },
    NoiceCursor = { link = "TermCursor" },
    NotifyDEBUGBorder = { link = "EightiesBlue" },
    NotifyDEBUGIcon = { link = "EightiesBlue" },
    NotifyDEBUGTitle = { link = "EightiesBlue" },
    NotifyERRORBorder = { link = "EightiesRed" },
    NotifyERRORIcon = { link = "EightiesRed" },
    NotifyERRORTitle = { link = "EightiesRed" },
    NotifyINFOBorder = { link = "EightiesAqua" },
    NotifyINFOIcon = { link = "EightiesAqua" },
    NotifyINFOTitle = { link = "EightiesAqua" },
    NotifyTRACEBorder = { link = "EightiesGreen" },
    NotifyTRACEIcon = { link = "EightiesGreen" },
    NotifyTRACETitle = { link = "EightiesGreen" },
    NotifyWARNBorder = { link = "EightiesYellow" },
    NotifyWARNIcon = { link = "EightiesYellow" },
    NotifyWARNTitle = { link = "EightiesYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.cyan },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "EightiesYellow" },
    DapUIBreakpointsDisabledLine = { link = "EightiesGray" },
    DapUIBreakpointsInfo = { link = "EightiesAqua" },
    DapUIBreakpointsLine = { link = "EightiesYellow" },
    DapUIBreakpointsPath = { link = "EightiesBlue" },
    DapUICurrentFrameName = { link = "EightiesPurple" },
    DapUIDecoration = { link = "EightiesPurple" },
    DapUIEndofBuffer = { link = "EightiesBg2" },
    DapUIFloatBorder = { link = "EightiesAqua" },
    DapUILineNumber = { link = "EightiesYellow" },
    DapUIModifiedValue = { link = "EightiesRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "EightiesBlue" },
    DapUISource = { link = "EightiesFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "EightiesBlue" },
    DapUIThread = { link = "EightiesBlue" },
    DapUIType = { link = "EightiesOrange" },
    DapUIUnavailable = { link = "EightiesGray" },
    DapUIWatchesEmpty = { link = "EightiesGray" },
    DapUIWatchesError = { link = "EightiesRed" },
    DapUIWatchesValue = { link = "EightiesYellow" },
    DapUIWinSelect = { link = "EightiesYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "EightiesGreenBold" },
    DiffviewFilePanelInsertions = { link = "EightiesGreenBold" },
    DiffviewFilePanelDeletions = { link = "EightiesRedBold" },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "EightiesRed" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "EightiesFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@namespace"] = { link = "EightiesFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "EightiesFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = {}, -- do not overwrite comments
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config EightiesConfig?
Eighties.setup = function(config)
  Eighties.config = vim.tbl_deep_extend("force", Eighties.config, config or {})
end

--- main load function
Eighties.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("eighties.nvim: you must use neovim 0.8 or higher")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "eighties"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Eighties
